### PR TITLE
feat: ref files for doc version 123 (sketch 62)

### PR DESCRIPTION
**Pull request by jedrichards**

### CODE REVIEW

**Review by christianklotz — APPROVED** [review]
✨

**Comment by christianklotz** [comment]
The update of the developer website is done separately, right?

**Comment by jedrichards** [comment]
I think we removed all the nitty gritty information about Sketch version to document version mappings from the developer website, and just link to this repo and the file format repo instead, to reduce the duplication of information.

**Comment by christianklotz** [comment]
Ah, we did indeed. Thank you

**Pull request merged**
